from __future__ import annotations

from typing import Protocol


class BlobStorage(Protocol):
    def put(self, data: bytes, *, content_type: str) -> str: ...
    def get(self, key: str) -> bytes: ...
    def exists(self, key: str) -> bool: ...
    def delete(self, key: str) -> None: ...
